#LOCAL
#spring.jpa.hibernate.ddl-auto=none
#spring.datasource.url=${LOCAL_JDBC_URL}
#spring.datasource.username=${LOCAL_DB_USER}
#spring.datasource.password=${LOCAL_DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=none
spring.datasource.url=${REMOTE_JDBC_URL}
spring.datasource.username=${REMOTE_DB_USER}
spring.datasource.password=${REMOTE_DB_PASSWORD}